export const propertyData = {
    homesAround59900: [
        {
            id: "1",
            imageUrl: "/house.jpg",
            price: 5490000, // Price in NPR
            acres: 0.23,
            address: "1234 Thamel Rd",
            city: "Kathmandu",
            state: "Bagmati",
            zip: "44600",
            propertyType: "Land",
        },
        {
            id: "2",
            imageUrl: "/house.jpg",
            price: 5490000,
            acres: 0.23,
            address: "5678 Lazimpat Rd",
            city: "Kathmandu",
            state: "Bagmati",
            zip: "44600",
            propertyType: "Land",
        },
        {
            id: "3",
            imageUrl: "/house.jpg",
            price: 5900000,
            acres: 0.23,
            address: "9101 Boudha St",
            city: "Kathmandu",
            state: "Bagmati",
            zip: "44600",
            propertyType: "Land",
        },
        {
            id: "4",
            imageUrl: "/house.jpg",
            price: 6500000,
            acres: 0.23,
            address: "1122 Patan Durbar Square",
            city: "Lalitpur",
            state: "Bagmati",
            zip: "44700",
            propertyType: "Land",
        },
    ],

    newestListings: [
        {
            id: "5",
            imageUrl: "/house.jpg",
            price: 36799000, // Price in NPR
            beds: 4,
            baths: 2,
            sqft: 2288,
            address: "123 New Home St",
            city: "Bhaktapur",
            state: "Bagmati",
            zip: "44800",
            propertyType: "Single-Family Home",
            isNew: true,
            newHoursAgo: 3,
        },
        {
            id: "6",
            imageUrl: "/house.jpg",
            price: 36899000,
            beds: 4,
            baths: 2,
            sqft: 2288,
            address: "124 New Home St",
            city: "Bhaktapur",
            state: "Bagmati",
            zip: "44800",
            propertyType: "Single-Family Home",
            isNew: true,
            newHoursAgo: 3,
        },
        {
            id: "7",
            imageUrl: "/house.jpg",
            price: 35999000,
            beds: 3,
            baths: 2,
            sqft: 1888,
            address: "125 New Home St",
            city: "Bhaktapur",
            state: "Bagmati",
            zip: "44800",
            propertyType: "Single-Family Home",
            isNew: true,
            newHoursAgo: 5,
        },
        {
            id: "8",
            imageUrl: "/house.jpg",
            price: 36999000,
            beds: 3,
            baths: 2,
            sqft: 2244,
            address: "126 New Home St",
            city: "Bhaktapur",
            state: "Bagmati",
            zip: "44800",
            propertyType: "Single-Family Home",
            isNew: true,
            newHoursAgo: 5,
        },
    ],

    upcomingOpenHouses: [
        {
            id: "9",
            imageUrl: "/house.jpg",
            price: 69990000,
            beds: 3,
            baths: 2,
            sqft: 2048,
            address: "1201 Sky Ridge Way",
            city: "Pokhara",
            state: "Gandaki",
            zip: "33700",
            propertyType: "Single-Family Home",
        },
        {
            id: "10",
            imageUrl: "/house.jpg",
            price: 32900000,
            beds: 3,
            baths: 2,
            sqft: 1491,
            address: "909 Wildwood Cir",
            city: "Patan",
            state: "Lalitpur",
            zip: "44700",
            propertyType: "Single-Family Home",
        },
        {
            id: "11",
            imageUrl: "/house.jpg",
            price: 33400000,
            beds: 3,
            baths: 2,
            sqft: 1411,
            address: "420 Royal Poinciana",
            city: "Patan",
            state: "Lalitpur",
            zip: "44700",
            propertyType: "Single-Family Home",
        },
        {
            id: "12",
            imageUrl: "/house.jpg",
            price: 32900000,
            beds: 3,
            baths: 2,
            sqft: 1491,
            address: "428 Royal Poinciana",
            city: "Patan",
            state: "Lalitpur",
            zip: "44700",
            propertyType: "Single-Family Home",
        },
    ],

    affordableHomes: [
        {
            id: "13",
            imageUrl: "/house.jpg",
            price: 1690000,
            acres: 0.989,
            address: "14208 Hillsborough Blvd",
            city: "Chitwan",
            state: "Chitwan",
            zip: "44200",
            propertyType: "Land",
            isNew: true,
            newHoursAgo: 2,
        },
        {
            id: "14",
            imageUrl: "/house.jpg",
            price: 2250000,
            acres: 0.23,
            address: "23332 Airway Ave",
            city: "Patan",
            state: "Lalitpur",
            zip: "44700",
            propertyType: "Land",
            isNew: true,
            newHoursAgo: 3,
        },
        {
            id: "15",
            imageUrl: "/house.jpg",
            price: 1370000,
            acres: 0.23,
            address: "14120 Bethel Ave",
            city: "Bhaktapur",
            state: "Bagmati",
            zip: "44800",
            propertyType: "Land",
            isNew: true,
            newHoursAgo: 10,
        },
        {
            id: "16",
            imageUrl: "/house.jpg",
            price: 2490000,
            acres: 0.23,
            address: "15088 Foresman Ave Lot 16",
            city: "Chitwan",
            state: "Chitwan",
            zip: "44200",
            propertyType: "Land",
            isNew: true,
            newHoursAgo: 10,
        },
    ],

    luxuryHomes: [
        {
            id: "17",
            imageUrl: "/house.jpg",
            price: 36799000,
            beds: 4,
            baths: 2,
            sqft: 2288,
            address: "14001 Pebble Ln",
            city: "Kathmandu",
            state: "Bagmati",
            zip: "44600",
            propertyType: "Single-Family Home",
            isNew: true,
            newHoursAgo: 5,
        },
        {
            id: "18",
            imageUrl: "/house.jpg",
            price: 36899000,
            beds: 4,
            baths: 2,
            sqft: 2288,
            address: "14002 Pebble Ln",
            city: "Kathmandu",
            state: "Bagmati",
            zip: "44600",
            propertyType: "Single-Family Home",
            isNew: true,
            newHoursAgo: 3,
        },
        {
            id: "19",
            imageUrl: "/house.jpg",
            price: 35999000,
            beds: 3,
            baths: 2,
            sqft: 1888,
            address: "14003 Pebble Ln",
            city: "Kathmandu",
            state: "Bagmati",
            zip: "44600",
            propertyType: "Single-Family Home",
            isNew: true,
            newHoursAgo: 5,
        },
        {
            id: "20",
            imageUrl: "/house.jpg",
            price: 35999000,
            beds: 3,
            baths: 2,
            sqft: 1488,
            address: "14004 Pebble Ln",
            city: "Kathmandu",
            state: "Bagmati",
            zip: "44600",
            propertyType: "Single-Family Home",
            isNew: true,
            newHoursAgo: 5,
        },
    ],
};